# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

#Darkmode
darkmode: never



# Personal info
name: Farid Saud
title: Data Scientist
email: gfs3@illinois.edu
phone: 224-266-4646
website: fsaudm.github.io

# Social links
twitter_username: jekyllrb
github_username:  fsaudm
instagram_username: faridsaudm
linkedin_username: faridsaud


# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: profile.jpg
about_content: | # This will include new lines to allow paragraphs
  I am a huge enthisiast of Machine Learning, currently pursuing a Master of Science in Statistics at the University of Illinois at Urbana-Champaign. I specialize in <mark>Data Science</mark>, <mark>Machine Learning</mark>, and <mark>Deep Learning</mark>. My work explores the impact of these technologies across various industries, including Finance, Technology, Civil Engineering, and Real Estate, aiming to generate significant value. 

  Currently, I am a team lead at the [Data Science Research Services](https://dsrs.illinois.edu/about/unit/team) unit, where we drive research within the GIES College of Business by assisting students, faculty, and staff with their data science, machine learning, computational infrastructure, and data acquisition needs. As I advance in my career as a Data Scientist, I am eager to dive deeper into Data Science itselft, and explore its applications and impact in the fields I mention above, as well as broader applications and the unique challenges different fields present. 

  I am committed to continuous learning and growth, and I am always looking for opportunities to expand my knowledge and skills. I cannot recommend enough [Kurzgesagt](https://www.youtube.com/watch?v=fa8k8IQ1_X0), [StatQuest](https://www.youtube.com/@statquest), and [Brilliant](https://brilliant.org/). Andrej Karpathy's [blog](https://karpathy.ai/) is amazing, and I am very excited about [Eureka Labs](https://eurekalabs.ai/)!

  Beyond academics, I like to follow the advancements in [Artificial Intelligence](https://www.youtube.com/watch?v=fa8k8IQ1_X0), Virtual & Augmented Reality (VR/AR), [fast cars](https://www.youtube.com/watch?v=nSqzp3kdAm4) and drones, and [video games](https://www.youtube.com/watch?v=8fbtx0D2Wyk). I also love traveling and exploring diverse cuisines. Additionally, I hold a Master of Science in Civil and Environmental Engineering from the University of Illinois at Urbana-Champaign.

# Within the realm of <mark>Construction Engineering and Management</mark>, I specialize in <mark>Project Management</mark>, <mark>Building Information Modeling (BIM)</mark>, and <mark>Virtual Design and Construction (VDC)</mark> and understanding their transformative potential in modern construction projects. I am actively seeking opportunities that allow me to expand my horizons and leverage these computational techniques to their full potential. 




# More Section
more_title: "A Little More About Me"
more_content: |
  Here are some additional details about me:
  
  - I recently achieved a 1-year streak on Duolingo for practicing Italian, Arabic, and Korean!
  - So far, I have traveled to [18 countries](https://visitedplaces.com/view/?map=world&projection=geoNaturalEarth1&theme=dark-blue&water=1&graticule=0&names=1&duration=2000&placeduration=100&slider=0&autoplay=0&autozoom=none&autostep=0&home=US&places=~US.daaa44_MX_PR_CO_EC.73aa64_PE_BR_AR_UY_ES_FR_NL_DE_CH_IT_AT_SE_DK) and 24 states in the US.

  

  For a traditional view of my academic and professional journey, you can check my [resume](https://uofi.box.com/s/q1jzz2jo1bou04atrciunc2lwbo3wrj0).

  


# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)



sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
