# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

#Darkmode
darkmode: never



# Personal info
name: Farid Saud
title: Data Scientist | Civil Engineer | Construction Project Engineer & Manager
email: gfs3@illinois.edu
phone: 224-266-4646
website: fsaudm.github.io

# Social links
twitter_username: jekyllrb
github_username:  fsaudm
instagram_username: faridsaudm
linkedin_username: faridsaud


# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a data enthusiast, currently pursuing a Master in Science degree in Statistics at the University of Illinois at Urbana-Champaign and building my career as a Data Scientist. Recently, I graduated with a Master's in Civil and Environmental Engineering from the University of Illinois at Urbana-Champaign, where I specialized in <mark>Construction Engineering and Management</mark>, <mark>SRIS</mark>, and <mark>Data Science</mark> and <mark>Machine Learning</mark>. While I have applied data science and machine learning tools and techniques to civil engineering and construction, I am eager to explore their broader applications across other industries/fields and challenges. 
  
  Within the realm of Construction Management, I am higly interested and specialized in <mark>Project Management</mark>, and <mark>Building Information Modeling (BIM)</mark> and <mark>Virtual Design and Construction (VDC)</mark> and understanding their transformative potential in modern construction projects. I am actively seeking opportunities that allow me to expand my horizons and leverage these computational techniques to their full potential. For a comprehensive, more traditional view of my academic and professional journey, please refer to my [CV](https://uofi.box.com/s/q1jzz2jo1bou04atrciunc2lwbo3wrj0).

  Beyond my academic and professional focus, I am actively interested in the advancements of Virtual Reality (VR) and Augmented Reality (AR), very quick vehicles and videogames. I have a profound passion for traveling and a deep love for food.


# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)



sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
