# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

#Darkmode
darkmode: never



# Personal info
name: Farid Saud
title: Data Scientist | Civil Engineer | Construction Project Engineer & Manager
email: gfs3@illinois.edu
phone: 224-266-4646
website: fsaudm.github.io

# Social links
twitter_username: jekyllrb
github_username:  fsaudm
instagram_username: faridsaudm
linkedin_username: faridsaud


# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: profile.jpg
about_content: | # This will include new lines to allow paragraphs
  I am a huge fan of Machine Learning, currently pursuing a Master of Science degree in Statistics at the University of Illinois at Urbana-Champaign. I specialize in <mark>Data Science</mark>, <mark>Machine Learning</mark>, and <mark>Deep Learning</mark>. I have worked with these tools and techniques, and explored how these impact different industries and fields, including Civil Engineering and Construction, Real Estate, Finance, Technology, among others, and how we can benefit and generate great value. 


  As I build my career as a Data Scientist, I am eager to explore its broader applications across other industries/fields and challenges these may pose. For a more traditional view of my academic and professional journey, please refer to my [CV](https://uofi.box.com/s/q1jzz2jo1bou04atrciunc2lwbo3wrj0).


  Beyond my academic and professional focus, I am interested in the advancements of Artificial Intelligence (AI) and Virtual & Augmented Reality (VR/VR), fast cars, and video games. I am very much travel-oriented, and I really love food. I also hold a M.S. in Civil and Environmental Engineering from the University of Illinois at Urbana-Champaign. 


# Within the realm of <mark>Construction Engineering and Management</mark>, I specialize in <mark>Project Management</mark>, <mark>Building Information Modeling (BIM)</mark>, and <mark>Virtual Design and Construction (VDC)</mark> and understanding their transformative potential in modern construction projects. I am actively seeking opportunities that allow me to expand my horizons and leverage these computational techniques to their full potential. 

  


# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)



sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
