# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Farid Saud
title: Civil Engineer & Data Scientist | Construction Engineering and Management
email: gfs3@illinois.edu
phone: 224-266-4646
website: fsaudm.github.io

# Social links
twitter_username: jekyllrb
github_username:  fsaudm
instagram_username: faridsaudm
linkedin_username: faridsaud


# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I recently graduated with a Master's in Civil and Environmental Engineering from the University of Illinois at Urbana-Champaign, where I specialized in Construction Engineering and Management, SRIS, and AI applications. Within the realm of Construction Management, I am higly interested and specialized in <mark>Building Information Modeling (BIM)</mark> and <mark>Virtual Design and Construction (VDC)</mark>, understanding their transformative potential in modern infrastructure projects. My passion lies at the intersection of <mark>deep learning</mark>, <mark>machine learning</mark>, and <mark>data science</mark>. While I have applied these techniques to civil engineering and construction, I am eager to explore their broader applications across various industries and challenges. As a fusion of engineer and data enthusiast, I am actively seeking opportunities that allow me to expand my horizons and leverage these computational techniques to their full potential. For a comprehensive view of my academic and professional journey, please refer to my [CV](https://drive.google.com/file/d/15XH2GQNulVMjeY3VDO7qOKipd9Xe0BeJ/view?usp=sharing).



# Education Section
# educaton_title: Education #(Use this to override about education section title)

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Publications Section
# Publications_title: Publications

# More Section
more_title: Relevant Coursework
more_content: | 
- Data Science for CEE
- Machine Learning for CEE
- Statistical Modeling
- Advanced Data Analysis
- Infrastructure Sensing
- Construction Optimization
- Construction Data Modeling
- Construction Engineering
- Construction Planning
- Cost Analysis
languages_title: Languages
languages_content: |
- Spanish: Native Language
- English: Full Professional Proficiency
- Italian: Professional Working Proficiency
- French: Beginner
- Arabic: Beginner

soft_skills_title: Soft Skills and Strengths
soft_skills_content: |
- Leadership
- Curiosity
- Flexibility
- Autonomy
- Adaptability
- Problem Solving
- Team Working
- Love Learning New Things
- Good Communication
- Diplomacy

professional_skills_title: Professional Skills
professional_skills_content: |
- Machine Learning
- Deep Learning
- BIM
- VDC
- Construction Management

it_skills_title: Information Technology Skills
it_skills_content: |
- Engineering Software and Tools: Autodesk AutoCAD, Civil 3D, REVIT, NAVISWORKS, Oracle PRIMAVERA P6, MS Projects
- Data Analysis: Python/R, Tableau
- Office Automation: MS Office (Excel & VBA, Word, PowerPoint)

programming_title: Programming and Data Manipulation
programming_content: |
- Python
- R
- Julia
- MATLAB
- C++
- SQL






# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
