# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Farid Saud
title: Graduate Student at UIUC
email: gfs3@illinois.edu
phone: 224-266-4646
website: fsaudm.github.io

# Social links
twitter_username: jekyllrb
github_username:  fsaudm
instagram_username: faridsaudm
linkedin_username: faridsaud


# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  I am gradaute student in the Civil and Environmental Engineering at the University of Illinois at Urbana-Champaign, focused on Construction Engineering and Management, SRIS, and AI. My research interests include <mark>artificial intelligence</mark>, <mark>machine learning</mark>, and <mark>deep learning</mark>.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# Publications Section
# Publications_title: Publications

# More Section
more_title: Honors & Awards
more_content: | 
  - To be continued

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
