# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

#Darkmode
darkmode: never



# Personal info
name: Farid Saud
title: Data Scientist
email: gfs3@illinois.edu
phone: 224-266-4646
website: fsaudm.github.io

# Social links
twitter_username: jekyllrb
github_username:  fsaudm
instagram_username: faridsaudm
linkedin_username: faridsaud


# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: profile.jpg
about_content: | # This will include new lines to allow paragraphs
  I am a huge enthisiast of Machine Learning, currently pursuing a Master of Science degree in Statistics at the University of Illinois at Urbana-Champaign. I specialize in <mark>Data Science</mark>, <mark>Machine Learning</mark>, and <mark>Deep Learning</mark>. My work explores the impact of these technologies across various industries, including Civil Engineering, Real Estate, Finance, and Technology, aiming to generate significant value. 

  As I advance in my career as a Data Scientist, I am eager to dive deeper into Data Science itselft, and explore its application and impact in the fields mentioned above, as well as broader applications and the unique challenges different fields present. For a traditional view of my academic and professional journey, please refer to my [resume](https://uofi.box.com/s/q1jzz2jo1bou04atrciunc2lwbo3wrj0).

  Beyond academics, I am interested in advancements in Artificial Intelligence (AI), Virtual & Augmented Reality (VR/AR), fast cars, and video games. I also love traveling and exploring diverse cuisines. Additionally, I hold a Master of Science in Civil and Environmental Engineering from the University of Illinois at Urbana-Champaign.

# Within the realm of <mark>Construction Engineering and Management</mark>, I specialize in <mark>Project Management</mark>, <mark>Building Information Modeling (BIM)</mark>, and <mark>Virtual Design and Construction (VDC)</mark> and understanding their transformative potential in modern construction projects. I am actively seeking opportunities that allow me to expand my horizons and leverage these computational techniques to their full potential. 

  


# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)



sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
